### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by bale-le** [justinlovelace/latent-diffusion-for-language#7]
Hello, I am very interested in your research. I encountered some issues while trying to replicate the code. When I execute the ” bash ./scripts/diffusion/text_diffusion_e2e.sh“ command, the following error is displayed:

Traceback (most recent call last):
  File "train_text_diffusion.py", line 206, in <module>
    main(args)
  File "train_text_diffusion.py", line 94, in main
    trainer.train()
  File "/data/yqh2022/code/latent-diffusion-for-language-main/diffusion/denoising_diffusion.py", line 757, in train
    self.sample()
  File "/data/yqh2022/.conda/envs/ld4lm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data/yqh2022/code/latent-diffusion-for-language-main/diffusion/denoising_diffusion.py", line 638, in sample
    metrics[f"model/{strategy}/{class_id_prefix}perplexity"] = evaluation.compute_perplexity(all_texts_list)
  File "/data/yqh2022/code/latent-diffusion-for-language-main/evaluation/evaluation.py", line 16, in compute_perplexity
    results = perplexity.compute(predictions=all_texts_list, model_id=model_id, device='cuda')
  File "/data/yqh2022/.conda/envs/ld4lm/lib/python3.8/site-packages/evaluate/module.py", line 444, in compute
    output = self._compute(**inputs, **compute_kwargs)
  File "/home/yqh2022/.cache/huggingface/modules/evaluate_modules/metrics/evaluate-metric--perplexity/8ab643ad86f568b7d1d5f7822373fa7401ff5ff0297ccf114b0ca6a33be96bc0/perplexity.py", line 117, in _compute
    tokenizer = AutoTokenizer.from_pretrained(model_id)
  File "/data/yqh2022/.conda/envs/ld4lm/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 549, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/data/yqh2022/.conda/envs/ld4lm/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 418, in get_tokenizer_config
    commit_hash = extract_commit_hash(resolved_config_file, commit_hash)
  File "/data/yqh2022/.conda/envs/ld4lm/lib/python3.8/site-packages/transformers/utils/hub.py", line 225, in extract_commit_hash
    search = re.search(r"snapshots/([^/]+)/", resolved_file)
  File "/data/yqh2022/.conda/envs/ld4lm/lib/python3.8/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

**Comment by bale-le** [comment]
By adding the parameter " model_id='gpt2-large' ", I have resolved this issue.
